version: "3"
services:
  db:
    image: mysql:latest
    container_name: mysql-docker
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=simple_forum
    volumes:
      - /Users/a123/go/docker-volumes/mysql:/var/lib/mysql
